EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = "587"
EMAIL_USERNAME = "miguelvieiradatascience@gmail.com"
EMAIL_PASSWORD = "Dat@37118983"
EMAIL_TO = "miguelvmesquitads@gmail.com"
WEBHOOK_URL = "https://google.com.br"